-- CreateTable
CREATE TABLE "BangGiaVL" (
    "id" SERIAL NOT NULL,
    "vatLieu" TEXT NOT NULL,
    "doDay" DOUBLE PRECISION NOT NULL,
    "donGiaVL" DOUBLE PRECISION NOT NULL,
    "tienBe" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "giaCat" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "donGiaLo" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "donGiaLoTappu" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "giaVat" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "tyTrong" DOUBLE PRECISION NOT NULL DEFAULT 7.85,

    CONSTRAINT "BangGiaVL_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CongTy" (
    "id" SERIAL NOT NULL,
    "tenCongTy" TEXT NOT NULL,
    "tiengNhat" TEXT NOT NULL DEFAULT '',
    "heSo_4_5mm" DOUBLE PRECISION NOT NULL DEFAULT 44,
    "heSo_duoi4_5mm" DOUBLE PRECISION NOT NULL DEFAULT 64,
    "isUuDai" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "CongTy_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DonHang" (
    "id" SERIAL NOT NULL,
    "maDon" TEXT NOT NULL,
    "tenCongTy" TEXT NOT NULL DEFAULT '',
    "ghiChu" TEXT NOT NULL DEFAULT '',
    "ngayTao" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tongTien" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "DonHang_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Panel" (
    "id" SERIAL NOT NULL,
    "donHangId" INTEGER NOT NULL,
    "tenTam" TEXT NOT NULL,
    "soLuong" INTEGER NOT NULL DEFAULT 1,
    "vatLieu" TEXT NOT NULL,
    "doDay" DOUBLE PRECISION NOT NULL,
    "x" DOUBLE PRECISION NOT NULL,
    "y" DOUBLE PRECISION NOT NULL,
    "maKhach" TEXT NOT NULL DEFAULT '',
    "loNho" INTEGER NOT NULL DEFAULT 0,
    "loLon" INTEGER NOT NULL DEFAULT 0,
    "soLoTappu" INTEGER NOT NULL DEFAULT 0,
    "soLoSara" INTEGER NOT NULL DEFAULT 0,
    "be" JSONB NOT NULL DEFAULT '[]',
    "pitchiGio" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "cuonGio" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "vatMm" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "giaVL" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "giaCat" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "giaCong" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "gia1Tam" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "allIn" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Panel_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "BangGiaVL_vatLieu_doDay_key" ON "BangGiaVL"("vatLieu", "doDay");

-- CreateIndex
CREATE UNIQUE INDEX "DonHang_maDon_key" ON "DonHang"("maDon");

-- AddForeignKey
ALTER TABLE "Panel" ADD CONSTRAINT "Panel_donHangId_fkey" FOREIGN KEY ("donHangId") REFERENCES "DonHang"("id") ON DELETE CASCADE ON UPDATE CASCADE;
